# Generated by Django 5.2.12 on 2026-07-13 10:06

import django.db.models.deletion
import django.utils.timezone
import modules.base.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0018_filefavorite'),
        ('chat', '0028_message_social_sent_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankRoshtat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('active', models.BooleanField(default=True, help_text='Whether this item is active and should be displayed', verbose_name='Active')),
                ('key', models.CharField(blank=True, help_text="Unique identifier for this record like 'contact_1'", max_length=255, null=True, unique=True)),
                ('name', models.CharField(help_text='Auto-generated from the chat message.', max_length=255, verbose_name='Name')),
                ('notes', models.TextField(blank=True, default='', help_text='Free-form notes about this prescription.', verbose_name='Notes')),
                ('attachment', modules.base.fields.AttachmentForeignKeyField(allowed_types=['image'], blank=True, help_text='Prescription image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_roshtat_images', to='base.attachment', upload_to='drmagdy/bank_roshtat/images', verbose_name='Image')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('message', models.OneToOneField(blank=True, help_text='The chat message this prescription was created from (one per message).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_roshtat', to='chat.message', verbose_name='Message')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Bank Roshtat',
                'verbose_name_plural': 'Bank Roshtat',
                'ordering': ['-created_at'],
            },
        ),
    ]
