# Generated by Django 5.2.12 on 2026-07-23 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_filefavorite'),
        ('drmagdy', '0001_initial'),
        ('whatsapp', '0016_whatsappaccount_conversation_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendTicketImageAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='', help_text='Optional message sent as the image caption.', verbose_name='Message')),
                ('partners', models.ManyToManyField(blank=True, help_text='Customers to send the ticket image to (filtered by the selected number).', related_name='drmagdy_send_ticket_image_actions', to='base.partner', verbose_name='Customers')),
                ('whatsapp_account', models.ForeignKey(help_text='The WhatsApp account (number) to send from.', on_delete=django.db.models.deletion.CASCADE, to='whatsapp.whatsappaccount', verbose_name='WhatsApp Number')),
            ],
            options={
                'verbose_name': 'Send Ticket Image',
            },
        ),
    ]
