# -*- coding: utf-8 -*-
"""
Data migration: convert ``support.ticket.files`` from a single FK
(``AttachmentForeignKeyField`` → ``files_id`` column) to an M2M
(``AttachmentManyToManyField`` → ``support_ticket_files`` join table),
PRESERVING existing attachments.

Why a real migration (not just sync_schema):
    ``files`` is an extension field, normally synced via ``sync_schema``. But
    ``sync_schema`` cannot do this change safely on a server that still has the
    old ``files_id`` column: its ``_field_exists('support_ticket', 'files')``
    matches the ``files_id`` FK-suffix and early-returns, so the M2M join table
    is NEVER created and the old ``files_id`` values are NEVER copied — the
    images would silently detach on deploy. This migration does it
    deterministically and idempotently as part of ``manage.py migrate``.

⚠️ DELIBERATELY uses raw SQL with hard-coded, verified names instead of reading
   the M2M field off the model. During ``manage.py migrate`` the extension
   system is INTENTIONALLY skipped (modules/base/apps.py: "Extension application
   skipped - migration command detected"), so the ``files`` M2M field is NOT on
   the Ticket model at migrate time — reading it would fail and the migration
   would silently do nothing. The names below are Django's deterministic M2M
   convention and were verified against the live table:
       table   : support_ticket_files
       columns : id (bigint PK), ticket_id (bigint), attachment_id (bigint)
       uniq    : (ticket_id, attachment_id)
       FKs     : ticket_id → support_ticket(id), attachment_id → base_attachment(id)

Idempotent + safe in any starting state (old VPS FK state, partial, or fresh):
    - join table already exists  → CREATE IF NOT EXISTS is a no-op
    - ``files_id`` already gone   → copy + drop are skipped
    - rows already copied         → NOT EXISTS skips duplicates
"""
from django.db import migrations


THROUGH_TABLE = "support_ticket_files"
SRC_COL = "ticket_id"
TGT_COL = "attachment_id"


def _column_exists(cursor, table, column):
    cursor.execute(
        "SELECT 1 FROM information_schema.columns "
        "WHERE table_name = %s AND column_name = %s",
        [table, column],
    )
    return cursor.fetchone() is not None


def forward(apps, schema_editor):
    with schema_editor.connection.cursor() as cur:
        # 1. Create the M2M join table if it doesn't exist yet. Exact Django M2M
        #    schema (verified against the live table). IF NOT EXISTS keeps it a
        #    no-op when sync_schema or a prior run already made it.
        cur.execute(
            f"""
            CREATE TABLE IF NOT EXISTS {THROUGH_TABLE} (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                {SRC_COL} BIGINT NOT NULL
                    REFERENCES support_ticket(id) DEFERRABLE INITIALLY DEFERRED,
                {TGT_COL} BIGINT NOT NULL
                    REFERENCES base_attachment(id) DEFERRABLE INITIALLY DEFERRED,
                CONSTRAINT {THROUGH_TABLE}_{SRC_COL}_{TGT_COL}_uniq
                    UNIQUE ({SRC_COL}, {TGT_COL})
            )
            """
        )
        # Helpful lookup indexes (Django creates these too). IF NOT EXISTS safe.
        cur.execute(
            f"CREATE INDEX IF NOT EXISTS {THROUGH_TABLE}_{SRC_COL}_idx "
            f"ON {THROUGH_TABLE} ({SRC_COL})"
        )
        cur.execute(
            f"CREATE INDEX IF NOT EXISTS {THROUGH_TABLE}_{TGT_COL}_idx "
            f"ON {THROUGH_TABLE} ({TGT_COL})"
        )

        # 2. Copy old single-FK data into the join table. NOT EXISTS keeps it
        #    idempotent (safe to re-run; skips rows already present).
        if _column_exists(cur, "support_ticket", "files_id"):
            cur.execute(
                f"INSERT INTO {THROUGH_TABLE} ({SRC_COL}, {TGT_COL}) "
                f"SELECT t.id, t.files_id FROM support_ticket t "
                f"WHERE t.files_id IS NOT NULL "
                f"AND NOT EXISTS ("
                f"  SELECT 1 FROM {THROUGH_TABLE} j "
                f"  WHERE j.{SRC_COL} = t.id AND j.{TGT_COL} = t.files_id"
                f")"
            )
            # 3. Drop the stale FK column now that its data is preserved.
            cur.execute("ALTER TABLE support_ticket DROP COLUMN IF EXISTS files_id")


def backward(apps, schema_editor):
    # Non-destructive reverse: restore an empty files_id FK column so the old
    # schema shape exists again. We intentionally do NOT collapse the M2M back
    # into it (a ticket may now have several images; there is no single value),
    # and we leave the join table in place so no attachment links are lost.
    with schema_editor.connection.cursor() as cur:
        if not _column_exists(cur, "support_ticket", "files_id"):
            cur.execute(
                "ALTER TABLE support_ticket "
                "ADD COLUMN files_id bigint NULL "
                "REFERENCES base_attachment(id) ON DELETE SET NULL"
            )


class Migration(migrations.Migration):

    dependencies = [
        ('drmagdy', '0002_sendticketimageaction'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
