# Generated by Django 5.2.12 on 2026-09-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drmagdy', '0003_ticket_files_fk_to_m2m'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelTicketAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('cancel_keep', 'Cancelled, keep the item'), ('cancel_return', 'Returned to the shelf')], default='cancel_keep', max_length=16, verbose_name='What happens to the item?')),
                ('reason', models.TextField(blank=True, default='', help_text='Optional reason, saved in the ticket chatter.', verbose_name='Reason')),
            ],
            options={
                'verbose_name': 'Cancel Ticket',
            },
        ),
    ]
